version: 2
updates:
  # Maintain dependencies for Go
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "22:00"
      timezone: "Asia/Tokyo"
    target-branch: "main"
    labels:
      - "dependencies"
      - "go"
    open-pull-requests-limit: 5
    groups:
      go-packages:
        patterns:
          - "*"

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "22:00"
      timezone: "Asia/Tokyo"
    target-branch: "main"
    labels:
      - "dependencies"
      - "github-actions"
    open-pull-requests-limit: 3
    groups:
      actions:
        patterns:
          - "*"
