name: Security Check

on: [push, pull_request]

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check for sensitive data
        run: |
          echo "Checking for sensitive data in repository..."

          # Check for potential tokens
          echo "Checking for exposed tokens..."
          ! grep -r "LINE_CHANNEL_TOKEN=[A-Za-z0-9]" .
          ! grep -r "LINE_USER_ID=[A-Za-z0-9]" .

          # Check for local config files
          echo "Checking for local config files..."
          ! find . -name "config.local.*"
          ! find . -name "*.local.*"

          # Check for log files
          echo "Checking for committed log files..."
          ! find . -name "*.log"
          ! find . -path "./logs/*"

          echo "Security check completed successfully!"

  go-security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.21"
          cache: true

      - name: Run gosec
        uses: securego/gosec@master
        with:
          args: ./...
